sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "ambito6666@gmail.com"
  - git config --global user.name "sujung You"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "gqT5HVl/HmRWqzFcSHZSWZBb+BAUdj/8CSNFLS/0oThFDbCEzkW8TAFqwGFLAm3Xq1XU6J5sF1jv8Rc
             CwdH1FPYLPh+2zUvGdBI6qZXPXdPbzlktC+okD++WroLNORD16yapLjN5Hr/o4MYBoz/0KtNvASzO9GtfBw/qsMmhr
             NHrK7X8vYJ9wyQ1Wx2PUPBWFXtKh41f+hpwZiEoVoQrcDdhPKu0VyDdHZkKk4XzKfFOz6cXxXHL65023ICivygwfu7
             TD8aawb6QvQS80v8s8MqgNMkNtcXqSR7FTgCKWMSLiqZ9i2uAgrU9xpZbgwJmo2P5nw76Gv8Zdjw8e7wDEwJy6bydS
             nSou5RsgcTM6vz5DwtbF/E5yBV41yJjd9h2DKQrTlYJt6XBqbB1LjvB4bGvSsOAjD4ea/CZzoJ8umX+eNMgodwSPTx
             u93sBIg4xO+XTjuukSsQedpnm3UpPVBr65ON8spJjeqvzXjPhqzq0wkzvsT/g0o4OnBkFGkUasNFAl2vsoer0ppWbZ
             5XzI4FyNWWhx1/Sm2NvxJkjf07YNCvPCpc6FJXcTOEJ46BkwzBEwG01jjG1GiN+rwkkjcZ3Oxi0UDBgMuWiNrZvmJl
             jJqQU/x2aZnB5t2b/PDMv/5r5GuW8ozrXCgp69vpq6SjuKMwfEDhSuyHR+tXg2xE="
branches:
  only:
    - master